### ISSUE TITLE
Revise Brigade Toolkit: Introduction

### ISSUE THREAD

**Issue by danhon** [codeforamerica/content-team#20]
Filed by @brielleplump in original content needs spreadsheet. 

Original document here: 

https://docs.google.com/document/d/1usHMpLu4FBdMTpfmQeQYz4Y4hfW-LXbGtTNpnMw20R4/edit

@brielleplump can you give an update/more information on how we can help with this piece of content?

**Comment by dschrimmer** [comment]
@brielleplump re: your email, update each item in the toolkit after it's been updated and you'd like content team to look at it. 

cc @danhon
