### ISSUE TITLE
Webpages for each of the 2015 Government Partners

### ISSUE THREAD

**Issue by danhon** [codeforamerica/content-team#48]
Originally filed by @nneditch in content needs spreadsheet.

**Comment by Jaime-Alexis** [comment]
Also addressed. @Danhon do you want me to close or just comment on others.

**Comment by danhon** [comment]
Just close, please!

Sent from my iPhone

On Feb 11, 2015, at 11:35 AM, Jaime-Alexis <notifications@github.com> wrote:

Also addressed. @Danhon do you want me to close or just comment on others.
On Feb 10, 2015 9:39 PM, "Dan Hon" <notifications@github.com> wrote:

> Originally filed by @nneditch <https://github.com/nneditch> in content
> needs spreadsheet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/content-team/issues/48>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/codeforamerica/content-team/issues/48#issuecomment-73913284>
.
