### ISSUE TITLE
DFD how-to documentation

### ISSUE THREAD

**Issue by danhon** [codeforamerica/content-team#5]

**Comment by danhon** [comment]
I met with Cyd yesterday to hear about tech-team content needs for DFD, i.e. a bunch of how-tos so far that can be form a collection. 

Roughly:

 - tech team will draft articles (cyd and frances have already started)
 - content team will edit for understandability-copyability etc
 - we will publish in the library (subject to change based on dan and cyd and overall website IA decisions, but publish in the library for now), tagged appropriately
 - content team would write a blog about it
 - hand over to marketing team can promote whenever/wherever they want

at some point (soon!) library needs to be able to support comments/forms of user feedback, as it is sitting in the passive/publish/broadcast mode of interaction at the moment.

**Comment by danhon** [comment]
@cydharrell @phae are you guys OK with closing this issue and creating issues for each how-to manual you'd like published?

**Comment by phae** [comment]
Sure, if that's what you'd prefer.

**Comment by phae** [comment]
Also, would like to catch up on this at some point, anyway. We need to talk about DFD in relation to Ceviche and how the documentation should support that product etc.

**Comment by danhon** [comment]
Tell you what, we can keep this one open as a rolling one meta-issue. 

What I don't know is what documentation you want to do, though, and I'd prefer each of those be tracked separately rather than as one big lump. 

Re DFD/Ceviche is that just a chat in Slack or do we need to do a Proper Meeting?

**Comment by phae** [comment]
For once, a proper meeting might be helpful because this might be a
whiteboard thing.

Frances Berriman
http://fberriman.com

**Comment by danhon** [comment]
I'll look for a time.

**Comment by danhon** [comment]
Closing this issue as we've created:

https://github.com/codeforamerica/content-team/issues/16 and
https://github.com/codeforamerica/content-team/issues/17
