### ISSUE TITLE
Webpage for each focus area : thesis, case studies, projects, partners

### ISSUE THREAD

**Issue by danhon** [codeforamerica/content-team#62]
Originally filed by @jmadans in content needs spreadsheet.

 - Currently aggregated in one page here: codeforamerica.org/focus

**Comment by Jaime-Alexis** [comment]
In progress with @alanjosephwilliams for Health. We'll still need to get Econ Dev, Safety and Justice up with help from that team. Also pinging @davidrleonard

**Comment by danhon** [comment]
Closing this and opening new issues for Econ Dev and Safety and Justice.
