### ISSUE TITLE
Process for Copy-Editing and Design

### ISSUE THREAD

**Issue by lynnfine** [codeforamerica/content-team#7]
We need to figure out a process for copy-editing and designing documents (manuals, toolkits, case studies) that content team and that the rest of the org creates. For example, I'm almost done with the Fellowship Toolkit and would love support from someone else to copy-edit it and manage the design process.

**Comment by danhon** [comment]
Lynn: I would suggest creating an issue for the Fellowship Toolkit saying that it needs to be published, rather than creating an issue for "process". We can then work through the process in that issue.
