### ISSUE TITLE
How Do I Know If I Have A Content Need?

### ISSUE THREAD

**Issue by danhon** [codeforamerica/content-team#9]
I'm working on a deck for this that can be presented at staff.

**Comment by daguar** [comment]
Rad, thanks — this'd be super helpful. :+1:

**Comment by danhon** [comment]
How Do I Know If I Have A Content Need

You might have a content need when: 

 - you are aware of a need that users have
 - it is a need that involves government delivery
 - you are working on something that improves government delivery against that need
 - you have learned something
 - that something will lead to better digital government if more people know about it

In the content team, we work with two levels of users. The users of what we produce are generally people who work in government, whose users are citizens. 

We should always be considering how what we are doing is helping to get to our end goal of producing 21st century governments.

**Comment by danhon** [comment]
@ladyson @dschrimmer thoughts?

**Comment by danhon** [comment]
Updated to:

* you have identified a *user* (e.g. a brigade leader, an urban planner, a procurement director);
* you have identified a *need* (e.g. they want to start a brigade, they want to make it easier to purchase SAAS);
* fulfilling the need results in *better government* (a brigade works with government, SAAS is a better model of buying software); and
* you have *actionable information or advice* on fulfilling that need.

**Comment by danhon** [comment]
Updated the github wiki, closing this now until it needs to be updated.
